# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.PAT }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYaml
    - name: Run Swagger Breakdown
      run: |
        python SwaggerBreakdown.py
    - name: 'Update version'
      run: |
          git config --global user.name "github-action"
          git add .
          git commit -am "Updated README with breakdown swaggers"
          git push  
