# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Breakdown swagger
      run: |
          go mod init swagger
          go install gopkg.in/yaml.v3@latest
          go run SwaggerBreakdown.go
    - name: 'Update repo'
      run: |
          git config --global user.email "danut.buse@example.com"
          git config --global user.name "github-action"
          git status
          git add .
          git commit -am "Updated README with breakdown swaggers"
          git push
